name: Format HTML CSS JS AND MD files
on:
  push:
    branches:
      - "*"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Prettier
        run: npm install -g prettier
      - name: Format code
        run: |
          npx prettier --write '**/*.{html,css,js}'
