name: Format HTML CSS JS AND MD files

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
      - name: Install Prettier
        run: npm install -g prettier
      - name: Format code
        run: |
          npx prettier --write '**/*.{html,css,js}'
