name: Perl Critic Check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  perl_critic_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Perl and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install perl
        sudo apt-get -y install cpanminus
        sudo cpanm Perl::Critic

    - name: Run Perl Critic
      run: |
        perlcritic .
